Test compose output for example deploy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -120,3 +120,18 @@ jobs:
           SAD_IMAGE_DIGEST: ${{ steps.docker_build.outputs.digest }}
           SAD_FOO: ${{ secrets.FOO_BETA }}
           SAD_BAR: ${{ secrets.BAR_BETA }}
+      - uses: webfactory/ssh-agent@v0.4.1
+      with:
+          ssh-private-key: |
+            echo ${{ secrets.PRIVATE_KEY }} | base64 -d
+      - name: Test Deployment
+        run: |
+          result=$(ssh ${{ secrets.SERVER }} cd jswny-sad-example-beta && docker-compose logs)
+          if echo "$result" | grep -q 'not found'; then
+            echo "One or more environment variables were not loaded correctly!"
+            echo "$result"
+            exit 1
+          else
+            exit 0
+          fi
+          
